services:
  - type: web
    name: mat-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: VITE_API_URL
        value: https://mat-backend.onrender.com
